version: "3"
services:
  tagcat:
    image: codewrightio/tagcat:latest
    environment:
      - EXPOSE_SWAGGER=true
    ports:
      - "5551:5551"
    volumes:
      - view.db:/app/view.db
      - meta.db:/app/meta.db
