name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: | 
        docker build . --file ./Tagcat.API/Dockerfile -t codewrightio/tagcat:latest
        docker build . --file ./Tagcat.Installer/Dockerfile -t codewrightio/tagcat-install:latest
